// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlepegruqphrtwmvvust.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZXBlZ3J1cXBocnR3bXZ2dXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDAwOTksImV4cCI6MjA2MDM3NjA5OX0.YJcuUckIesEKf0c_D7SzpIuDCY81II34bGKWZ1KKC_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);